### ISSUE TITLE
CI/CD

### ISSUE THREAD

**Issue by bart84ek** [repo-mono/land_queue#3]
Using GCP Cloud Builds

For each branch trigger build process - code checks + tests
Trigger deploy on merge to master - gcp app engine deploy

**Comment by bootstraponline** [comment]
would github actions work? https://github.com/features/actions

**Comment by bart84ek** [comment]
Github Actions is also an option.
I decided to go with Cloud Builds because we already use GCP to deploy, and we can setup CI/CD with terraform..

And yes, it's already done.

**Comment by bootstraponline** [comment]
Sounds excellent! Thanks.
